### ISSUE TITLE
MethodCall.resolve() does not apply ElementMatcher to private methods in a DynamicType under construction

### ISSUE THREAD

**Issue by ljnelson** [raphw/byte-buddy#1006]
I will try to refine this bug report as I learn more.  I thought it was worth filing anyway because `ElementMatchers` are used so much and are so central to ByteBuddy.

I'm defining a `DynamicType`.  As part of doing this, I am defining two `private` methods: `produce` and `inject`.

At one point in my program I do this:

    MethodCall.invoke(ElementMatchers.named("inject"))...

…i.e. "please invoke the `inject` method I defined elsewhere in this dynamic type".

I get an exception indicating that (as it happens) two methods (!) meet this criteria (even though I've only defined one `inject` method).  When I debug into the resolution code, I see that my `produce` method has somehow matched the `ElementMatchers.named("inject")` matcher.  I'm not sure how this can happen.

I'm attaching a NetBeans debugger screenshot showing `MethodCall.java` at line 812.  Here, `candidates.size()` is `2`.  You can see that the `matcher` is `name(equals(inject))` and one of the two candidates is `produce`.

![Screen Shot 2021-01-30 at 11 13 52 AM](https://user-images.githubusercontent.com/80764/106365903-5b17f500-62ed-11eb-9a90-aee3aec0dd1e.png)

**Comment by ljnelson** [comment]
Naturally, the act of filing this bug report made me look closer 😄  and now I'm thinking that `ElementMatchers.named("inject")` is working fine, but the second part of that `CompoundList.of()` call is strange.

I am not familiar with this area of the `MethodCall` code, but it looks like `instrumentedType.getDeclaredMethods().filter(isMethod().and(not(ElementMatchers.isVirtual())))` will just include all declared methods in the `DynamicType` under construction (that, obviously, are not virtual).  In my case, this will include all `private` methods I've defined internally (which in my case happen to be `produce` and `inject`), no matter what the `matcher` says.  That feels wrong.

**Comment by ljnelson** [comment]
I've edited the title to better reflect where I think the problem may lie.

**Comment by raphw** [comment]
You are very right, the filter matcher is missing. I fixed it on master, thanks!

**Comment by ljnelson** [comment]
Hi, @raphw; I'm, er, not sure that you did.  See:

https://github.com/raphw/byte-buddy/blob/636c274333744ff3d44cb5ace1da926a400e02a2/byte-buddy-dep/src/main/java/net/bytebuddy/implementation/MethodCall.java#L810

As of 2021-02-01 line 810 still doesn't feature the `matcher`.

**Comment by raphw** [comment]
Silly me pushed it to an unrelated branch, thanks for noticing!
